FROM redis:6.2.5
WORKDIR /usr/src/redis
CMD ["redis-server", "6001.conf"]
CMD ["redis-server", "6002.conf"]
CMD ["redis-server", "6003.conf"]
CMD ["bash", "sen1.sh", "start"]
CMD ["bash", "sen2.sh", "start"]
CMD ["bash", "sen3.sh", "start"]