version: '3'
services:
  backend:
    build: ./backend
    ports: 
      - "9999:9999"
    volumes:
      - ./backend:/usr/src/app

  redis:
    build: ./redis
    ports:
      - "8081:8081"
    volumes:
      - ./redis:/usr/src/redis